---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    auto-config.enabled: false

  messaging.services:
    - name: "messaging"
      kind: "file-based-messaging"
      binding: "C:message.json"
